=== 5mehulhelp5/Magento-2-Extension/etc/mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright (c) 2020 Unbxd Inc.
 */
-->

<!--
/**
 * Init development:
 * @author andy
 * @email andyworkbase@gmail.com
 * @team MageCloud
 */
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configType"/>
    <xs:complexType name="fieldType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="fieldsType">
        <xs:sequence>
            <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element type="fieldsType" name="fields"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="configType">
        <xs:sequence>
            <xs:element type="productType" name="product"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== 5mehulhelp5/Magento-2-Extension/etc/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright (c) 2020 Unbxd Inc.
 */
-->

<!--
/**
 * Init development:
 * @author andy
 * @email andyworkbase@gmail.com
 * @team MageCloud
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Sales:etc/mapping.xsd">
    <product>
        <fields>
            <field name="entity_id" type="unique_id" />
            <field name="name" type="title" />
            <field name="image" type="image_url" />
            <field name="url_key" type="product_url" />
            <field name="quantity_and_stock_status" type="availability" />
            <field name="category" type="category_path_id" />
        </fields>
    </product>
</config>
